# Production environment values
replicaCount: 3

image:
  tag: "v1.0.0"

env:
  - name: APP_VERSION
    value: "1.0.0"
  - name: ENVIRONMENT
    value: "production"
  - name: DEBUG
    value: "False"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
